# Generated by Django 5.0 on 2023-12-25 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("department_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("head_of_department", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DepartmentSpecific",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("task_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("diagnosis", models.CharField(max_length=255)),
                ("treatment_plan", models.TextField()),
                ("prescription", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("appointment_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MediCare.department",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="department",
            name="department_specific_tasks",
            field=models.ManyToManyField(
                related_name="department", to="MediCare.departmentspecific"
            ),
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("doctor_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone_number", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("specialisation", models.CharField(max_length=255)),
                ("address", models.TextField(max_length=255)),
                (
                    "appointments",
                    models.ManyToManyField(
                        related_name="doctors_appointments", to="MediCare.appointment"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="departmentspecific",
            name="doctor",
            field=models.ManyToManyField(
                related_name="medical_records", to="MediCare.doctor"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctors",
            field=models.ManyToManyField(
                related_name="appointment_doctors", to="MediCare.doctor"
            ),
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone_number", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField(max_length=255)),
                (
                    "medical_record",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MediCare.medicalrecord",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="departmentspecific",
            name="patient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="MediCare.patient"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="MediCare.patient"
            ),
        ),
    ]
