# Generated by Django 5.0 on 2023-12-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MediCare", "0002_alter_appointment_doctors_alter_doctor_appointments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="doctors",
        ),
        migrations.AlterField(
            model_name="doctor",
            name="appointments",
            field=models.ManyToManyField(
                related_name="doctors", to="MediCare.appointment"
            ),
        ),
    ]
