# Generated by Django 5.0 on 2023-12-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MediCare", "0003_remove_appointment_doctors_alter_doctor_appointments"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="NSS",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="patient",
            name="NSS",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
