# Generated by Django 5.0 on 2023-12-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MediCare", "0004_doctor_nss_patient_nss"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="department",
        ),
        migrations.RemoveField(
            model_name="departmentspecific",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="appointments",
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ManyToManyField(related_name="doctors", to="MediCare.doctor"),
        ),
        migrations.AddField(
            model_name="departmentspecific",
            name="appointment",
            field=models.ManyToManyField(
                related_name="appointments", to="MediCare.appointment"
            ),
        ),
    ]
