# Generated by Django 5.0 on 2023-12-25 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MediCare", "0005_remove_appointment_department_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departmentspecific",
            name="doctor",
        ),
    ]
