# Generated by Django 5.0 on 2023-12-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MediCare", "0006_remove_departmentspecific_doctor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="department_specific_tasks",
        ),
        migrations.AddField(
            model_name="departmentspecific",
            name="department",
            field=models.ManyToManyField(
                related_name="department", to="MediCare.department"
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="doctor",
            field=models.ManyToManyField(
                related_name="doctor_record", to="MediCare.doctor"
            ),
        ),
    ]
