# Generated by Django 5.0 on 2023-12-27 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MediCare", "0007_remove_department_department_specific_tasks_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departmentspecific",
            name="appointment",
        ),
        migrations.RemoveField(
            model_name="departmentspecific",
            name="department",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="medical_record",
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="DepartmentSpecific",
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="MedicalRecord",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
    ]
