# Generated by Django 5.0 on 2023-12-27 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MediCare", "0010_alter_visit_appointment_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visit",
            name="Doctor",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="Patient",
        ),
        migrations.RemoveField(
            model_name="treatmentplan",
            name="Medical_Record",
        ),
        migrations.RemoveField(
            model_name="visit",
            name="Patient",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="Treatment_Plan",
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="MedicalRecord",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
        migrations.DeleteModel(
            name="Visit",
        ),
        migrations.DeleteModel(
            name="Prescription",
        ),
        migrations.DeleteModel(
            name="TreatmentPlan",
        ),
    ]
