# Generated by Django 5.0 on 2023-12-27 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("MediCare", "0011_remove_visit_doctor_remove_medicalrecord_patient_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("Doctor_ID", models.AutoField(primary_key=True, serialize=False)),
                ("NSS", models.CharField(max_length=255)),
                ("First_Name", models.CharField(max_length=255)),
                ("Last_Name", models.CharField(max_length=255)),
                ("Specialisation", models.CharField(max_length=255)),
                ("Phone_Number", models.CharField(max_length=20)),
                ("Email", models.EmailField(max_length=254)),
                ("Address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("Patient_ID", models.AutoField(primary_key=True, serialize=False)),
                ("NSS", models.CharField(max_length=255)),
                ("First_Name", models.CharField(max_length=255)),
                ("Last_Name", models.CharField(max_length=255)),
                ("Phone_Number", models.CharField(max_length=20)),
                ("Email", models.EmailField(max_length=254)),
                ("Address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                ("Record_ID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MediCare.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TreatmentPlan",
            fields=[
                ("Plan_ID", models.AutoField(primary_key=True, serialize=False)),
                ("Diagnosis", models.TextField()),
                ("Treatment_Details", models.TextField()),
                (
                    "Medical_Record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MediCare.medicalrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "Prescription_ID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("Medication", models.CharField(max_length=255)),
                ("Dose", models.CharField(max_length=255)),
                ("Serial_Number", models.CharField(max_length=255)),
                ("Prescription_Date", models.DateField()),
                (
                    "Treatment_Plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MediCare.treatmentplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                ("Visit_ID", models.AutoField(primary_key=True, serialize=False)),
                ("Consultation_Date", models.DateField(blank=True, null=True)),
                ("Appointment_Date", models.DateField(blank=True, null=True)),
                ("Visit_Time", models.TimeField(blank=True)),
                (
                    "Doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MediCare.doctor",
                    ),
                ),
                (
                    "Patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MediCare.patient",
                    ),
                ),
            ],
        ),
    ]
