# Generated by Django 5.0 on 2024-01-19 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MediCare", "0012_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="treatment_plan",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="MediCare.treatmentplan",
            ),
        ),
    ]
