# Generated by Django 5.0 on 2024-01-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MediCare", "0013_visit_treatment_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="Visits",
            field=models.ManyToManyField(
                related_name="medical_records", to="MediCare.visit"
            ),
        ),
    ]
